SmartDev\MainBundle\Entity\Composant:
    type: entity
    table: null
    repositoryClass: SmartDev\MainBundle\Entity\ComposantRepository
    oneToOne:
        licence:
            targetEntity: Licence
    oneToOne:
        typeComposant:
            targetEntity: TypeComposant
    oneToOne:
        natureComposant:
            targetEntity: NatureComposant
    
    oneToMany:
        versionComposant:
            targetEntity: VersionCmposant
            mappedBy: Composant  
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        titreComposant:
            type: string
            length: 255
            column: TitreComposant
        descriptionComposant:
            type: string
            length: 255
            column: DescriptionComposant
        visibiliteComposant:
            type: boolean
            column: VisibiliteComposant
            
    lifecycleCallbacks: {  }
