SmartDev\MainBundle\Entity\TypeProduit:
    type: entity
    table: null
    repositoryClass: SmartDev\MainBundle\Entity\TypeProduitRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nomTypeProduit:
            type: string
            length: 255
            column: NomTypeProduit
    lifecycleCallbacks: {  }
