SmartDev\MainBundle\Entity\TypeComposant:
    type: entity
    table: null
    repositoryClass: SmartDev\MainBundle\Entity\TypeComposantRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nomTypeComposant:
            type: string
            length: 255
            column: NomTypeComposant
    lifecycleCallbacks: {  }
