SmartDev\MainBundle\Entity\VersionProduit:
    type: entity
    table: null
    repositoryClass: SmartDev\MainBundle\Entity\VersionProduitRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nomVersionProduit:
            type: string
            length: 255
            column: NomVersionProduit
        dateVersionProduit:
            type: datetime
            column: DateVersionProduit
    lifecycleCallbacks: {  }
