smart_dev_main_homepage:
    pattern:  /main
    defaults: { _controller: SmartDevMainBundle:Default:index }

smart_dev_main_componentsDisplayPage:
    pattern: /display/components
    defaults: { _controller: SmartDevMainBundle:GeneralDisplay:displayComponents }

smart_dev_main_productsDisplayPage:
    pattern : /display/products
    defaults : { _controller: SmartDevMainBundle:GeneralDisplay:displayProducts }
smart_dev_main_ajouter_composant:
    pattern:  /ajoutercomposant
    defaults: { _controller: SmartDevMainBundle:Default:ajouter_composant  }