parameters:
#    smart_dev_main.example.class: SmartDev\MainBundle\Example

services:
#    smart_dev_main.example:
#        class: %smart_dev_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
