parameters:
#    chedy_hates_orma.example.class: ChedyHatesORM\ABundle\Example

services:
#    chedy_hates_orma.example:
#        class: %chedy_hates_orma.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
