chedy_hates_orma:
    resource: "@ChedyHatesORMABundle/Resources/config/routing.yml"
    prefix:   /

smart_dev_main:
    resource: "@SmartDevMainBundle/Resources/config/routing.yml"
    prefix:   /

