<?php

namespace ChedyHatesORM\ABundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JergRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JergRepository extends EntityRepository
{
}
