<?php

namespace SmartDev\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProgrammeProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgrammeProduitRepository extends EntityRepository
{
}
