<?php

namespace SmartDev\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VersionCmposantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VersionCmposantRepository extends EntityRepository
{
}
